Prevent ints from being converted to float when importing
tokenmill/accelerated-text pull request #317
Opened 2021-04-13 14:01 UTC by zmedelis

2021-04-14 08:05 UTC, rokasramas requested changes
Sorry, I missed the message in slack yesterday. The `data.entities.data-files` ns should be kept as is, this is not an anti-pattern in clojure, and there are many instances where this kind of structure is used in the repository. The main idea is that we lose hierarchy when namespaces are at the same level, in this instance, `row-selection` contains only specific utility functions, and is not as important as `data-files` ns.

2021-04-14 08:33 UTC, zmedelis commented
>The `data.entities.data-files` ns should be kept as is

Rolled back the NS name change and moved the coercion code to its own NS.

2021-04-15 07:09 UTC, rokasramas requested changes

2021-04-15 07:09 UTC, rokasramas commented on api/test/api/datomic_fixtures.clj
> +  (:require api.config
dropping [ ] is unusual, maybe this was unintended?

2021-04-19 10:50 UTC, rokasramas approved these changes

2021-04-19 10:50 UTC, merged